name: 'nps'
version: '1.0.0'

profile: 'nps'

model-paths: ["nps/models"]
analysis-paths: ["nps/analyses"]
test-paths: ["nps/tests"]
seed-paths: ["nps/seeds"]
macro-paths: ["nps/macros"]
snapshot-paths: ["nps/snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
    nps:
      staging:
        +schema: staging
        base:
          +materialized: view
        stage:
          +materialized: table
      marts:
        +schema: marts
        +materialized: table
