version: 2

sources:
  - name: raw
    description: "Parse out the json object"
    database: nps_warehouse      
    schema: raw                 
    tables:
      - name: parks
      - name: places
      - name: campgrounds
      - name: thingstodo
      - name: activities
      - name: alerts
      - name: events
      - name: feepassess
      - name: parkinglots
      - name: topics
      - name: tours
      - name: visitorcenters