with events as (
    select *
    from {{ source('raw', 'events') }}
)

select
    events.state_code,
    events.timestamp as loaded_at,
    v:"id"::string as event_id,
    v:"eventid"::string as event_legacy_id,
    v:"sitecode"::string as park_code,
    v:"sitetype"::string as site_type,
    v:"title"::string as title,
    v:"parkfullname"::string as park_full_name,
    v:"description"::string as description,
    v:"category"::string as category,
    v:"categoryid"::string as category_id,
    v:"types"::variant as types,
    v:"tags"::variant as tags,
    v:"date"::string as event_date,
    v:"datestart"::string as date_start,
    v:"dateend"::string as date_end,
    v:"dates"::variant as dates,
    v:"timeinfo"::string as time_info,
    v:"times"::variant as times,
    v:"isallday"::string as is_all_day,
    v:"isrecurring"::string as is_recurring,
    v:"recurrencerule"::string as recurrence_rule,
    v:"recurrencedatestart"::string as recurrence_date_start,
    v:"recurrencedateend"::string as recurrence_date_end,
    v:"isfree"::string as is_free,
    v:"feeinfo"::string as fee_info,
    v:"isregresrequired"::string as is_registration_required,
    v:"regresinfo"::string as registration_info,
    v:"regresurl"::string as registration_url,
    v:"location"::string as location,
    v:"latitude"::string as latitude,
    v:"longitude"::string as longitude,
    v:"contactname"::string as contact_name,
    v:"contactemailaddress"::string as contact_email_address,
    v:"contacttelephonenumber"::string as contact_telephone_number,
    v:"organizationname"::string as organization_name,
    v:"portalname"::string as portal_name,
    v:"subjectname"::string as subject_name,
    v:"infourl"::string as info_url,
    v:"imageidlist"::string as image_id_list,
    v:"images"::variant as images,
    v:"datetimecreated"::string as datetime_created,
    v:"datetimeupdated"::string as datetime_updated
from events
